{{- if .Values.secretProvider.create }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: db-password-provider
  namespace: {{ .Values.namespace }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.projectId }}/secrets/db-password/versions/latest"
        path: "db-password"
{{- end }}